on:
    workflow_dispatch:
      inputs:
        package:
          required: true
          type: string

name: Publish Package

jobs:
    release-core:
        uses: ./.github/workflows/release-package.yml
        with:
            package: ${{ inputs.package }}
